### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [Eren5960/JoinStats#3]
how do i setup the plugin? in the console i just get this message

[20:57:59] [Server thread/INFO]: Enabling JoinStats v1.0.1

[JoinStats] Welcome to JoinStats setup wizard.

[JoinStats] Available providers:

[JoinStats] [0] => Yaml

[JoinStats] [1] => Json

**Comment by xerenahmed** [comment]
Type 0 for Yaml or type 1 for json. Just press whatever you want if you say I have to only use it.

**Comment by ghost** [comment]
I already did that though and it did literally nothing that’s why I’m asking how to set it up
